// Static UI contract checks for the incision agent workbench.
import fs from "node:fs";
import assert from "node:assert/strict";

const html = fs.readFileSync("incision_agent.html", "utf8");
const js = fs.readFileSync("incision_agent_main.js", "utf8");
const tools = fs.readFileSync("incision_tools.js", "utf8");

assert.ok(html.includes('id="boundaryStatus"'), "workbench exposes tumor boundary status");
assert.ok(html.includes('id="anatomyPreview"'), "workbench exposes live anatomy preview for selected tumor center");
assert.ok(html.includes('id="exportTumorBtn"'), "workbench exposes tumor export button");
assert.ok(html.includes('id="importTumorBtn"'), "workbench exposes tumor import button");
assert.ok(html.includes('id="tumorImportFile"'), "workbench exposes hidden tumor import file input");
assert.ok(html.includes('id="secondaryCueState"'), "workbench exposes secondary cue status");
assert.ok(html.includes('id="importSecondaryCueBtn"'), "workbench exposes secondary cue import action");
assert.ok(html.includes('id="secondaryCueImportFile"'), "workbench exposes hidden secondary cue import file input");
assert.ok(html.includes('id="secondaryCueConfirmed"'), "workbench captures manual secondary cue confirmation");
assert.ok(html.includes("低置信度线索"), "workbench labels secondary cues as low confidence");
assert.ok(html.includes('id="reviewerName"'), "workbench captures clinician reviewer identity");
assert.ok(html.includes('id="reviewDecision"'), "workbench exposes clinician review decision");
assert.ok(html.includes('id="reviewNotes"'), "workbench exposes clinician review notes");
assert.ok(html.includes('id="guardrailDetails"'), "workbench exposes guardrail detail feedback");
assert.ok(html.includes('id="directionSource"'), "workbench exposes direction source explanation");
assert.ok(html.includes('id="agentGate"'), "workbench exposes agent trace gate feedback");
assert.ok(html.includes('id="undoEditBtn"'), "workbench exposes clinician edit undo");
assert.ok(html.includes('id="redoEditBtn"'), "workbench exposes clinician edit redo");
assert.ok(html.includes('id="editHistoryState"'), "workbench exposes clinician edit history status");
assert.ok(html.includes('id="agentExecutionList"'), "workbench exposes Agent execution events list");
assert.ok(html.includes('id="agentPlanList"'), "workbench exposes Agent ReAct plan list");
assert.ok(html.includes("execution-event"), "workbench styles Agent execution events");
assert.ok(html.includes("react-plan-step"), "workbench styles Agent ReAct plan steps");
assert.ok(html.includes('id="agentComparison"'), "workbench exposes backend agent candidate comparison");
assert.ok(html.includes('id="approveCandidateBtn"'), "workbench exposes candidate approval action");
assert.ok(html.includes('id="rejectCandidateBtn"'), "workbench exposes candidate rejection action");
assert.ok(html.includes('id="candidateWidth"'), "workbench exposes fusiform width and ratio metric");
assert.ok(html.includes('id="candidateTipAngle"'), "workbench exposes fusiform tip angle metric");
assert.ok(js.includes("exportTumorJson"), "workbench implements tumor JSON export");
assert.ok(js.includes("importTumorFile"), "workbench implements tumor JSON import");
assert.ok(js.includes("applyImportedTumor"), "workbench applies imported tumor payloads");
assert.ok(js.includes("browser-export-privacy-preflight/v0.1"), "browser export preflight has a schema");
assert.ok(js.includes("exportPreflightPasses(payload"), "JSON exports run browser privacy preflight");
assert.ok(js.includes("导出隐私预检未通过"), "browser preflight blocks unsafe exports with feedback");
assert.ok(js.includes("raw_media_flag_true"), "browser preflight catches raw media flags");
assert.ok(js.includes("secret_value_present"), "browser preflight catches unredacted secrets");
assert.ok(js.includes("pii_pattern_present"), "browser preflight catches direct PII patterns");
assert.ok(js.includes('!leaf.toLowerCase().endsWith("_at")'), "browser preflight does not flag timestamps as phone numbers");
assert.ok(js.includes("summarizeTumorBoundary"), "workbench renders deterministic boundary summaries");
assert.ok(tools.includes("units_per_mm"), "tumor boundary summary exports coordinate-to-mm scale for audit");
assert.ok(tools.includes("summary_axis"), "tumor boundary summary exports summary axis for audit");
assert.ok(tools.includes("summary_normal"), "tumor boundary summary exports summary normal for audit");
assert.ok(js.includes("summarizeTumorInputQuality"), "workbench renders tumor input quality summaries");
assert.ok(js.includes("classifyRegion(S.verts[S.lesion]"), "workbench derives anatomy preview from selected tumor center");
assert.ok(js.includes("当前点位分区"), "workbench labels live anatomy preview in Chinese");
assert.ok(js.includes("updateAnatomyPreview"), "workbench refreshes anatomy preview when the selected point changes");
assert.ok(js.includes("tumorQualityFor"), "workbench keeps tumor quality in review exports");
assert.ok(js.includes("tumor_boundary_summary"), "review records include tumor boundary summary geometry");
assert.ok(js.includes("boundarySummaryFor(result.tumor, result)"), "review records summarize tumor boundary against the saved candidate axis");
assert.ok(js.includes("肿物输入提示"), "markdown report includes tumor input quality warnings");
assert.ok(js.includes("肿物边界摘要"), "markdown report includes tumor boundary summary");
assert.ok(js.includes("梭形包络"), "markdown report includes fusiform outline and boundary envelope metrics");
assert.ok(js.includes("normalizeSecondaryCuePayload"), "workbench normalizes secondary cue imports");
assert.ok(js.includes("secondary_cues"), "review exports include secondary cue summaries");
assert.ok(js.includes("used_for_geometry: false"), "secondary cues never drive geometry");
assert.ok(js.includes("used_for_agent_prompt: false"), "secondary cues are not sent to the agent prompt");
assert.ok(js.includes("辅助线索仅随审阅导出，不发送给 Agent"), "privacy copy keeps secondary cues out of agent requests");
assert.ok(js.includes("tip_angle_error_deg"), "workbench renders fusiform tip angle error");
assert.ok(js.includes("incision-review-record/v0.3"), "review records use explicit review workflow schema");
assert.ok(js.includes("approved_for_discussion"), "review records support clinician approval");
assert.ok(js.includes("rejected_by_clinician"), "review records support clinician rejection");
assert.ok(js.includes("audit_events"), "review records include audit events");
assert.ok(js.includes("guardrail_summary"), "review records include guardrail summary");
assert.ok(js.includes("review_gate"), "review records include review gate state");
assert.ok(js.includes("candidate_edit_session"), "review records include clinician edit session state");
assert.ok(js.includes("candidate-edit-session/v0.1"), "clinician edit session has an explicit schema");
assert.ok(js.includes("undoEditSnapshot"), "workbench implements clinician edit undo");
assert.ok(js.includes("redoEditSnapshot"), "workbench implements clinician edit redo");
assert.ok(js.includes("commitEditSnapshot(\"endpoint_drag\")"), "endpoint dragging commits provenance history");
assert.ok(js.includes("agent_trace_gate"), "review records include agent trace gate state");
assert.ok(js.includes("sensitive_structure_inspection"), "review records include sensitive structure inspection");
assert.ok(js.includes("agent_react_plan"), "review records include Agent ReAct plan state");
assert.ok(js.includes("agent_execution_events"), "review records include Agent execution events");
assert.ok(js.includes("renderAgentExecutionEvents"), "workbench renders Agent execution events");
assert.ok(js.includes("renderAgentReactPlan"), "workbench renders Agent ReAct plan steps");
assert.ok(js.includes("observed_actions"), "ReAct plan UI shows observed tool actions");
assert.ok(js.includes("trace indexes"), "ReAct plan UI shows linked trace indexes");
assert.ok(js.includes("agent-trace-gate/v0.1"), "agent trace gate has an explicit schema");
assert.ok(js.includes("AGENT_TRACE_GATE_REQUIRED"), "workbench defines required agent tool actions");
assert.ok(js.includes("summarize_tumor_input_quality"), "agent gate requires tumor input quality tool");
assert.ok(js.includes("inspect_sensitive_structures"), "agent gate requires sensitive structure inspection tool");
assert.ok(js.includes("linear_subcutaneous_incision"), "agent gate accepts linear incision generation tool");
assert.ok(js.includes("fusiform_cutaneous_incision"), "agent gate accepts fusiform incision generation tool");
assert.ok(js.includes("preview_incision_on_face"), "agent gate requires deterministic face preview before review");
assert.ok(js.includes("Agent 工具 trace 未通过门控"), "approval is blocked when agent trace gate fails");
assert.ok(js.includes("Agent 工具门控"), "markdown report includes agent trace gate status");
assert.ok(js.includes("Agent ReAct 计划"), "markdown report includes Agent ReAct plan status");
assert.ok(js.includes("candidate_comparison"), "review export includes candidate comparison");
assert.ok(js.includes("candidate_alternatives"), "review export includes backend candidate alternatives");
assert.ok(js.includes("agent_orchestration_audit"), "review export includes backend orchestration audit");
assert.ok(js.includes("renderAgentComparison"), "workbench renders backend candidate comparison");
assert.ok(js.includes("agentAlternativeResult"), "workbench can save backend agent alternatives as review records");
assert.ok(js.includes("alternative.sensitive_structure_inspection"), "saved backend alternatives keep sensitive inspection");
assert.ok(js.includes("已保存 ${backendAlternatives.length} 个后端方向备选"), "variant save action prefers backend alternatives");
assert.ok(js.includes("formatRecoveredFailureSummary"), "workbench formats recovered tool failures");
assert.ok(js.includes("Agent 恢复详情"), "markdown report includes recovered failure details");
assert.ok(js.includes("已跳过失败变体并继续比较"), "recovered failure summary explains candidate skip behavior");
assert.ok(js.includes("不是临床推荐或手术指令"), "candidate comparison warns it is not clinical recommendation");
assert.ok(js.includes("reviewReadiness"), "review workflow validates approval readiness");
assert.ok(js.includes("highGuardrailWarnings"), "review workflow detects high guardrail warnings");
assert.ok(js.includes("live_overlay_ready"), "review gate records live overlay readiness");
assert.ok(js.includes("handleAgentStreamEvent"), "workbench consumes agent SSE trace events");
assert.ok(js.includes("stream: true"), "workbench prefers streaming agent trace");
assert.ok(js.includes('event === "trace_gate"'), "workbench consumes agent trace gate SSE events");
assert.ok(js.includes('event === "execution_event"'), "workbench consumes Agent execution SSE events");
assert.ok(js.includes('event === "react_plan"'), "workbench consumes Agent ReAct plan SSE events");
assert.ok(js.includes("Agent 执行事件"), "markdown report includes Agent execution event status");
assert.ok(js.includes("Agent 工具门控已通过"), "workbench reports successful SSE trace gate");
assert.ok(js.includes("Agent ReAct 计划已通过"), "workbench reports successful ReAct plan SSE event");
assert.ok(js.includes("SSE trace 不可用"), "workbench reports JSON fallback when streaming is unavailable");
assert.ok(js.includes("建议覆盖项"), "markdown report includes suggested override details");
assert.ok(js.includes("protective_direction"), "workbench displays protective direction guardrail suggestions");
assert.ok(js.includes("directionSourceLabel"), "workbench labels RSTL direction source");
assert.ok(js.includes("皱襞/边界辅助线索：只读审阅，不参与几何"), "workbench explains secondary cues do not drive direction geometry");
assert.ok(js.includes("医生人工覆盖已记录"), "workbench exposes manual direction override state");
assert.ok(js.includes("RSTL 来源"), "markdown report includes direction source provenance");
assert.ok(js.includes("最近敏感游离缘"), "markdown report includes sensitive free-margin distance");
assert.ok(js.includes("候选版本"), "markdown report includes candidate version provenance");
assert.ok(js.includes("发送到实时叠加前，请先确认当前候选草案"), "live overlay requires candidate approval");
assert.ok(js.includes("当前候选有高风险 guardrail"), "high-risk approval requires review notes");

console.log("test_incision_agent_ui: tumor boundary IO and review workflow assertions passed");
