// Static UI contract checks for incision overlay on the live 2D page.
import fs from "node:fs";
import assert from "node:assert/strict";

const html = fs.readFileSync("index.html", "utf8");
const main = fs.readFileSync("main.js", "utf8");
const render = fs.readFileSync("render.js", "utf8");
const mode3d = fs.readFileSync("mode3d.js", "utf8");
const three3d = fs.readFileSync("three3d.js", "utf8");
const source = fs.readFileSync("pipeline/source.js", "utf8");
const loop = fs.readFileSync("pipeline/loop.js", "utf8");
const exporter = fs.readFileSync("export_canvas.js", "utf8");

assert.ok(html.includes('accept="image/*,video/*"'), "live page accepts uploaded photos and videos");
assert.ok(html.includes('id="camBtn"'), "live page exposes camera entry for realtime overlay");
assert.ok(html.includes('id="exportBtn"'), "live page exposes export action");
assert.ok(html.includes('id="incisionOverlayQa"'), "live page exposes visible incision overlay QA state");
assert.ok(html.includes("切口叠加 QA"), "live page labels visible overlay QA as engineering state");
assert.ok(source.includes('setSource(prepared.source, "image"'), "uploaded photos enter the shared live render source");
assert.ok(source.includes('setSource(els.video, "video"'), "uploaded videos enter the shared live render source");
assert.ok(source.includes('setSource(els.video, "camera"'), "camera frames enter the shared live render source");
assert.ok(loop.includes('sourceState.sourceKind !== "image"'), "video and camera sources schedule continuous overlay frames");
assert.ok(main.includes("applyStagedIncisionOverlay"), "live page loads staged incision overlay payloads");
assert.ok(main.includes("validateIncisionOverlay(overlay)"), "live page validates incision overlay payloads before rendering");
assert.ok(main.includes("renderState.incisionOverlay = overlay"), "live page stores validated incision overlay in render state");
assert.ok(main.includes("setIncisionOverlayQa"), "live page shows pending overlay QA feedback after loading a candidate");
assert.ok(main.includes("上传照片、视频或开启摄像头后，会随 RSTL 一起显示"), "live page gives explicit overlay feedback");
assert.ok(main.includes("buildZoomCards(refreshStaticImage)"), "live page rebuilds zoom cards after loading incision overlay");
assert.ok(main.includes("createCanvasRecordingController"), "live page uses the tested canvas export controller");
assert.ok(main.includes("canvas: els.canvas"), "live page exports the rendered main canvas, including incision overlay");
assert.ok(exporter.includes("canvas.captureStream(fps)"), "export controller records the canvas stream");
assert.ok(exporter.includes('mimeType: "video/webm"'), "export controller records playable webm output");
assert.ok(render.includes("drawIncisionOverlay(lm"), "renderer draws incision overlay on every frame");
assert.ok(render.includes("measureIncisionOverlayRegistration"), "renderer measures incision overlay projection registration");
assert.ok(render.includes("measureIncisionOverlayJitter"), "renderer measures live incision overlay rolling jitter");
assert.ok(render.includes("incisionOverlay.registration.pass"), "renderer records passing overlay registration diagnostics");
assert.ok(render.includes("incisionOverlay.registration.fail"), "renderer records failing overlay registration diagnostics");
assert.ok(render.includes("incisionOverlay.registration.bboxDiagonalPx"), "renderer records overlay registration bbox metric");
assert.ok(render.includes("incisionOverlay.stability.rmsPx"), "renderer records overlay stability rms metric");
assert.ok(render.includes("incision-overlay-runtime-diagnostics/v0.1"), "renderer exports runtime overlay diagnostics section");
assert.ok(render.includes('setDiagnosticSection("incision_overlay_runtime"'), "renderer publishes sanitized overlay diagnostics section");
assert.ok(render.includes("exported_landmarks: false"), "overlay diagnostics do not export landmark coordinates");
assert.ok(render.includes("updateIncisionOverlayQa(registration, stability)"), "renderer updates visible overlay QA from measured results");
assert.ok(render.includes("投射需复核"), "renderer surfaces registration failure feedback");
assert.ok(render.includes("抖动需复核"), "renderer surfaces stability failure feedback");
assert.ok(render.includes("叠加稳定"), "renderer surfaces stable overlay feedback");
assert.ok(render.includes("切口候选"), "zoom strip exposes a dedicated incision candidate detail card");
assert.ok(render.includes("incisionOverlayBounds"), "renderer computes incision overlay bounds for detail zoom");
assert.ok(render.includes("overlay.tumor?.center_ref"), "incision zoom includes tumor center");
assert.ok(render.includes("overlay.tumor?.boundary_refs"), "incision zoom includes tumor boundary");
assert.ok(render.includes("overlay.candidate?.polyline_refs"), "incision zoom includes candidate incision line");
assert.ok(render.includes("mapSurfaceRefs(refs, lm"), "incision zoom maps surface refs through runtime landmarks");
assert.ok(three3d.includes("setIncisionOverlay(overlay, verts, tris)"), "3D viewer can render incision overlay surface refs");
assert.ok(three3d.includes("setIncisionOverlayPoints(overlay3d)"), "3D viewer can render mapped overlay points");
assert.ok(three3d.includes("tumor_boundary_points"), "3D viewer renders tumor boundary points");
assert.ok(three3d.includes("candidate_points"), "3D viewer renders candidate incision points");
assert.ok(mode3d.includes("applyIncisionOverlayToViewer(disp, faces)"), "3D route applies incision overlay after building viewer geometry");
assert.ok(mode3d.includes("mediaPipeOverlayToFlamePoints"), "3D route maps MediaPipe incision refs onto FLAME demo view");
assert.ok(mode3d.includes("incision_overlay_3d_view"), "3D route publishes sanitized overlay view diagnostics");
assert.ok(mode3d.includes("exported_raw_pixels: false"), "3D overlay diagnostics do not export raw pixels");

console.log("test_live_incision_overlay_ui: live overlay UI assertions passed");
