export interface LiveDomElements {
  video: HTMLVideoElement;
  canvas: HTMLCanvasElement;
  msg: HTMLElement;
  mainWrap: HTMLElement;
  upload: HTMLButtonElement;
  file: HTMLInputElement;
  cam: HTMLButtonElement;
  pause: HTMLButtonElement;
  export: HTMLButtonElement;
  tmpl: HTMLSelectElement;
  density: HTMLInputElement;
  smooth: HTMLInputElement;
  opacity: HTMLInputElement;
  prov: HTMLElement;
  restoreAtlas: HTMLButtonElement;
  densityVal: HTMLElement;
  smoothVal: HTMLElement;
  opacityVal: HTMLElement;
  clip: HTMLInputElement;
  handOcc: HTMLInputElement;
  mirror: HTMLInputElement;
  bands: HTMLInputElement;
  zoom: HTMLInputElement;
  zoomStrip: HTMLElement;
  meshPts: HTMLInputElement;
  routeSel: HTMLSelectElement;
  route3dPanel: HTMLElement;
  reconDemo: HTMLButtonElement;
  routeModeHint: HTMLElement;
  threeDWorkflowCard: HTMLElement;
  incisionWorkflowCard: HTMLElement;
  reconScan: HTMLButtonElement;
  view3d: HTMLButtonElement;
  project3d: HTMLButtonElement;
  reset3d: HTMLButtonElement;
  cloudFitFlame: HTMLButtonElement;
  flameStd: HTMLInputElement;
  flameHeadToggleWrap: HTMLElement;
  twinTexture: HTMLInputElement;
  twinTextureWrap: HTMLElement;
  scanPanel: HTMLElement;
  scanProgressVal: HTMLElement;
  scanProgressBar: HTMLElement;
  scanYawVal: HTMLElement;
  scanYawLeft: HTMLElement;
  scanYawMid: HTMLElement;
  scanYawRight: HTMLElement;
  scanToast: HTMLElement;
  reconStatus: HTMLElement;
  three: HTMLCanvasElement;
  badge: HTMLElement;
  live: HTMLElement;
  fps: HTMLElement;
  qualityVal: HTMLElement;
  qualityBar: HTMLElement;
  statState: HTMLElement;
  statFace: HTMLElement;
  statYaw: HTMLElement;
  statLines: HTMLElement;
  incisionOverlayQa: HTMLElement;
  incisionOverlayQaState: HTMLElement;
  incisionOverlayQaDetail: HTMLElement;
}

export const els: LiveDomElements;
export let ctx: CanvasRenderingContext2D | null;
export function bindDom(root?: ParentNode | Document): LiveDomElements;
export function clearDomBinding(): void;
